[package]
name = "aoc22"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
partial_sort = "0.1.2"
queues = "1.1.0"
parseline = { git = "https://github.com/albheim/parseline" }